/**
 * Contract and network configuration.
 * Override these via NEXT_PUBLIC_* environment variables.
 */

export const CONTRACT_ID = process.env.NEXT_PUBLIC_CONTRACT_ID || "CD3TE3IAHM737P236XZL2OYU275ZKD6MN7YH7PYYAXYIGEH55OPEWYJC";
export const NETWORK_PASSPHRASE = process.env.NEXT_PUBLIC_NETWORK_PASSPHRASE || "Test SDF Network ; September 2015";
export const RPC_URL = process.env.NEXT_PUBLIC_RPC_URL || "https://soroban-testnet.stellar.org";
export const NETWORK_NAME = process.env.NEXT_PUBLIC_NETWORK_NAME || "TESTNET";
export const TESTNET_USDC_TOKEN_ID = process.env.NEXT_PUBLIC_TESTNET_USDC_TOKEN_ID || "CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75";
export const TESTNET_EURC_TOKEN_ID = process.env.NEXT_PUBLIC_TESTNET_EURC_TOKEN_ID || "GDHU6WRG4IEQXM5NZ4BMPKOXHW76MZM4Y2IEMFDVXBSDP6SJY4ITNPP";
