name: Upptime

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  statuses: write

jobs:
  summary:
    name: Summary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  response-time:
    name: Response Time
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@master
        env:
          NOTIFICATION_SLACK: ${{ secrets.NOTIFICATION_SLACK }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TYPE: response-time

  graphs:
    name: Graphs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TYPE: graphs

  static-site:
    name: Static Site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TYPE: static-site
